# Generated by Django 4.2.2 on 2023-06-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactinformation_feedback_servives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='image',
        ),
    ]
