# Generated by Django 4.2.2 on 2023-06-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_feedback_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servives',
            new_name='Services',
        ),
    ]
