# Generated by Django 4.2.2 on 2023-06-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_servives_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
