# Generated by Django 4.2.2 on 2023-06-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(max_length=2)),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=70)),
                ('row1', models.CharField(max_length=300)),
                ('row2', models.CharField(max_length=300)),
                ('row3', models.CharField(max_length=300)),
            ],
        ),
    ]
